version: '3.0'
services:
  web:
    volumes:
      - /Users/vivek/workspace/devops-template/web:/home/critique/web
  
  ui:
    volumes:
      - /Users/vivek/workspace/devops-template/ui:/home/critique/ui

  c-mongo:
    volumes: 
      - /Users/vivek/workspace/devops-template/mongo:/data/db
  
  c-redis:
    volumes: 
      - /Users/vivek/workspace/devops-template/redis:/data
  
  c-kafka:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
